eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: employee
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    account:
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:2000/account
      password: my-secret-pw
    playground:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: my-secret-pw
      username: root
      url: jdbc:mysql://localhost:2000/playground
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: 'true'
# spring.cloud.config.uri is the spring cloud config server endpoint from where we can load all the employee app properties from
#  cloud:
#    config:
#      uri: http://localhost:8888

application:
  config:
    company-url: http://localhost:8081/company

# this is not required as the Spring Boot's Tomcat Server starts on port 8080 by default
server:
  port: 8080
