package com.example.webapp.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import lombok.*;

import java.util.List;

@Setter
@Getter
@EqualsAndHashCode
@ToString
@Builder
@DynamoDBTable(tableName = "product")
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String productId;
    @DynamoDBRangeKey
    private String productName;
    private double price;
    private double weight;
    private List<Tag> tags;
}